//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CodeStorage.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CodeStorageEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CodeStorageEntities object using the connection string found in the 'CodeStorageEntities' section of the application configuration file.
        /// </summary>
        public CodeStorageEntities() : base("name=CodeStorageEntities", "CodeStorageEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CodeStorageEntities object.
        /// </summary>
        public CodeStorageEntities(string connectionString) : base(connectionString, "CodeStorageEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CodeStorageEntities object.
        /// </summary>
        public CodeStorageEntities(EntityConnection connection) : base(connection, "CodeStorageEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Codes> Codes1
        {
            get
            {
                if ((_Codes1 == null))
                {
                    _Codes1 = base.CreateObjectSet<Codes>("Codes1");
                }
                return _Codes1;
            }
        }
        private ObjectSet<Codes> _Codes1;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Codes1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCodes1(Codes codes)
        {
            base.AddObject("Codes1", codes);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CodeStorageModel", Name="Codes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Codes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Codes object.
        /// </summary>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="codeID">Initial value of the CodeID property.</param>
        public static Codes CreateCodes(global::System.String code, global::System.Int64 codeID)
        {
            Codes codes = new Codes();
            codes.Code = code;
            codes.CodeID = codeID;
            return codes;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false, "Code");
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CodeID
        {
            get
            {
                return _CodeID;
            }
            set
            {
                if (_CodeID != value)
                {
                    OnCodeIDChanging(value);
                    ReportPropertyChanging("CodeID");
                    _CodeID = StructuralObject.SetValidValue(value, "CodeID");
                    ReportPropertyChanged("CodeID");
                    OnCodeIDChanged();
                }
            }
        }
        private global::System.Int64 _CodeID;
        partial void OnCodeIDChanging(global::System.Int64 value);
        partial void OnCodeIDChanged();

        #endregion

    }

    #endregion

}
